server:
  port: 8020
  
spring:
  application:
    name: eureka-client-book
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123@peer2:8762/eureka, http://user:123@peer1:8761/eureka
  instance:
    prefer-ip-address: true