server:
  port: 8010
Spring:
  application: 
    name: eureka-client-user
    
eureka:
  client:
    defaultZone: http://peer2:8762/eureka, http://peer1:8761/eureka
    
  instance:
    prefer-ip-address: true
  
