server:
  port: 8010
Spring:
  application: 
    name: eureka-client-user
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123@peer2:8762/eureka, http://user:123@peer1:8761/eureka 
  instance:
    prefer-ip-address: true
  
