spring:
  application:
    name: services-discovery-eureka

    
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123@peer2:8762/eureka, http://user:123@peer1:8761/eureka
    
---

spring:
  profiles: peer1
  
server:
  port: 8761
  

  
eureka:
  instance:
    hostname: peer1
    
---

spring:
  profiles: peer2
  
server:
  port: 8762
  
eureka:
  instance:
    hostname: peer2
  

  